version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.1
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.1
    - 7.0.7
  - dependency-name: "@hookform/resolvers"
    versions:
    - 1.3.2
    - 1.3.3
    - 1.3.4
    - 1.3.5
    - 1.3.6
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: yup
    versions:
    - 0.32.8
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.12.1
  - dependency-name: timecop
    versions:
    - 0.9.2
    - 0.9.3
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: octokit
    versions:
    - 4.20.0
